/* =============================================================================
 * catalog.js — AUTO-GENERATED by scripts/build-catalog.mjs from TMDB.
 * Do not edit by hand; re-run the script to refresh. Mood axes + score are
 * derived from real signals (genres, runtime, rating, keywords) — see derive.mjs.
 * Generated 2026-07-09, 60 titles.
 * ========================================================================== */

const GENRES = ["Action","Adventure","Animation","Comedy","Crime","Documentary","Drama","Fantasy","Horror","Romance","Sci-Fi","Thriller"];

const MOOD_AXES = [
  { key: 'brain',     low: 'Switch off',   high: 'Make me think' },
  { key: 'intensity', low: 'Cozy',         high: 'Intense'       },
  { key: 'levity',    low: 'Serious',      high: 'Light & funny' },
];

const CATALOG = [
  {
    "id": "breaking-bad",
    "title": "Breaking Bad",
    "year": 2008,
    "kind": "Series",
    "genres": [
      "Drama",
      "Crime"
    ],
    "runtime": 56,
    "brain": 0.67,
    "intensity": 0.58,
    "levity": 0.17,
    "score": 88,
    "hook": "Change the equation.",
    "poster": "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Stan"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "the-shawshank-redemption",
    "title": "The Shawshank Redemption",
    "year": 1994,
    "kind": "Film",
    "genres": [
      "Drama",
      "Crime"
    ],
    "runtime": 142,
    "brain": 0.72,
    "intensity": 0.62,
    "levity": 0.32,
    "score": 87,
    "hook": "Fear can hold you prisoner. Hope can set you free.",
    "poster": "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    "providers": {
      "US": [
        "AMC+ Roku Premium Channel",
        "AMC"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "HBO Max",
        "HBO Max Amazon Channel"
      ]
    }
  },
  {
    "id": "the-godfather",
    "title": "The Godfather",
    "year": 1972,
    "kind": "Film",
    "genres": [
      "Drama",
      "Crime"
    ],
    "runtime": 175,
    "brain": 0.76,
    "intensity": 0.77,
    "levity": 0.24,
    "score": 86,
    "hook": "An offer you can't refuse.",
    "poster": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    "providers": {
      "US": [
        "fuboTV",
        "Paramount Plus Premium",
        "Paramount+ Amazon Channel",
        "YouTube TV",
        "Paramount+ Roku Premium Channel"
      ],
      "GB": [
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "CA": [
        "Crave",
        "Paramount Plus",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "BINGE",
        "Paramount Plus",
        "Foxtel Now",
        "Stan",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "the-dark-knight",
    "title": "The Dark Knight",
    "year": 2008,
    "kind": "Film",
    "genres": [
      "Action",
      "Crime",
      "Thriller"
    ],
    "runtime": 152,
    "brain": 0.58,
    "intensity": 0.83,
    "levity": 0.29,
    "score": 85,
    "hook": "Welcome to a world without rules.",
    "poster": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "Netflix",
        "Amazon Prime Video",
        "HBO Max Amazon Channel",
        "Netflix Standard with Ads",
        "Amazon Prime Video with Ads",
        "HBO Max"
      ],
      "CA": [
        "Netflix",
        "Crave",
        "Netflix Standard with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Amazon Prime Video",
        "Foxtel Now",
        "HBO Max",
        "Amazon Prime Video with Ads",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Amazon Prime Video",
        "JioHotstar",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "spirited-away",
    "title": "Spirited Away",
    "year": 2001,
    "kind": "Film",
    "genres": [
      "Animation",
      "Adventure",
      "Fantasy"
    ],
    "runtime": 125,
    "brain": 0.43,
    "intensity": 0.4,
    "levity": 0.67,
    "score": 85,
    "hook": "Beyond the tunnel was a mysterious town.",
    "poster": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "the-godfather-part-ii",
    "title": "The Godfather Part II",
    "year": 1974,
    "kind": "Film",
    "genres": [
      "Drama",
      "Crime"
    ],
    "runtime": 202,
    "brain": 0.86,
    "intensity": 0.74,
    "levity": 0.22,
    "score": 85,
    "hook": "The rise and fall of the Corleone empire.",
    "poster": "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    "providers": {
      "US": [
        "fuboTV",
        "Paramount Plus Premium",
        "Paramount+ Amazon Channel",
        "YouTube TV",
        "Paramount+ Roku Premium Channel"
      ],
      "GB": [
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "CA": [
        "Crave",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "BINGE",
        "Paramount Plus",
        "Foxtel Now",
        "Stan",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "schindler-s-list",
    "title": "Schindler's List",
    "year": 1993,
    "kind": "Film",
    "genres": [
      "Drama"
    ],
    "runtime": 195,
    "brain": 0.95,
    "intensity": 0.78,
    "levity": 0.2,
    "score": 85,
    "hook": "Whoever saves one life, saves the world entire.",
    "poster": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Crave Amazon Channel"
      ],
      "AU": [
        "BINGE",
        "Paramount+ Amazon Channel",
        "Foxtel Now"
      ],
      "IN": [
        "Amazon Prime Video",
        "JioHotstar",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "one-piece",
    "title": "One Piece",
    "year": 1999,
    "kind": "Series",
    "genres": [
      "Comedy",
      "Animation"
    ],
    "runtime": 24,
    "brain": 0.37,
    "intensity": 0.33,
    "levity": 0.9,
    "score": 85,
    "hook": "Set sail for One Piece!",
    "poster": "https://image.tmdb.org/t/p/w500/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Hulu",
        "Crunchyroll",
        "Crunchyroll Amazon Channel",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Netflix",
        "Crunchyroll",
        "Sky Go",
        "Crunchyroll Amazon Channel",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Crunchyroll Amazon Channel",
        "Crunchyroll",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads",
        "Crunchyroll",
        "Crunchyroll Amazon Channel"
      ],
      "IN": [
        "Crunchyroll",
        "Sony Liv",
        "Crunchyroll Amazon Channel"
      ]
    }
  },
  {
    "id": "rick-and-morty",
    "title": "Rick and Morty",
    "year": 2013,
    "kind": "Series",
    "genres": [
      "Animation",
      "Comedy"
    ],
    "runtime": 24,
    "brain": 0.43,
    "intensity": 0.33,
    "levity": 0.84,
    "score": 85,
    "hook": "Science makes sense, family doesn't.",
    "poster": "https://image.tmdb.org/t/p/w500/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg",
    "providers": {
      "US": [
        "Hulu",
        "HBO Max Amazon Channel",
        "YouTube TV",
        "Adult Swim",
        "HBO Max"
      ],
      "GB": [
        "Netflix",
        "HBO Max Amazon Channel",
        "Now TV",
        "Netflix Standard with Ads",
        "HBO Max"
      ],
      "CA": [
        "StackTV Amazon Channel",
        "fuboTV"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "better-call-saul",
    "title": "Better Call Saul",
    "year": 2015,
    "kind": "Series",
    "genres": [
      "Crime",
      "Drama"
    ],
    "runtime": 70,
    "brain": 0.67,
    "intensity": 0.58,
    "levity": 0.17,
    "score": 85,
    "hook": "Putting the \"criminal\" in \"criminal lawyer.\"",
    "poster": "https://image.tmdb.org/t/p/w500/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Stan"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "avatar-the-last-airbender",
    "title": "Avatar: The Last Airbender",
    "year": 2005,
    "kind": "Series",
    "genres": [
      "Animation"
    ],
    "runtime": 24,
    "brain": 0.42,
    "intensity": 0.38,
    "levity": 0.83,
    "score": 85,
    "hook": "Water. Earth. Fire. Air.",
    "poster": "https://image.tmdb.org/t/p/w500/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Paramount Plus Premium",
        "Paramount Plus Essential",
        "Paramount Plus Apple TV Channel ",
        "Paramount+ Amazon Channel",
        "Paramount+ Roku Premium Channel",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Netflix",
        "Paramount Plus",
        "Sky Go",
        "Paramount+ Amazon Channel",
        "Netflix Standard with Ads",
        "Paramount Plus Apple TV Channel ",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "CA": [
        "Netflix",
        "Crave",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Netflix Standard with Ads",
        "Paramount Plus Apple TV Channel ",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Netflix",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Netflix Standard with Ads",
        "Paramount Plus Apple TV Channel ",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "arcane",
    "title": "Arcane",
    "year": 2021,
    "kind": "Series",
    "genres": [
      "Animation"
    ],
    "runtime": 51,
    "brain": 0.42,
    "intensity": 0.44,
    "levity": 0.71,
    "score": 85,
    "hook": "The hunt is on.",
    "poster": "https://image.tmdb.org/t/p/w500/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "the-lord-of-the-rings-the-return-of-the-",
    "title": "The Lord of the Rings: The Return of the King",
    "year": 2003,
    "kind": "Film",
    "genres": [
      "Adventure",
      "Fantasy",
      "Action"
    ],
    "runtime": 201,
    "brain": 0.53,
    "intensity": 0.71,
    "levity": 0.49,
    "score": 84,
    "hook": "The eye of the enemy is moving.",
    "poster": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Netflix",
        "Stan",
        "Netflix Standard with Ads",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Netflix",
        "JioHotstar",
        "VI movies and tv"
      ]
    }
  },
  {
    "id": "the-lord-of-the-rings-the-fellowship-of-",
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "year": 2001,
    "kind": "Film",
    "genres": [
      "Adventure",
      "Fantasy",
      "Action"
    ],
    "runtime": 179,
    "brain": 0.5,
    "intensity": 0.69,
    "levity": 0.45,
    "score": 84,
    "hook": "One ring to rule them all.",
    "poster": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Netflix",
        "Stan",
        "Netflix Standard with Ads",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Netflix",
        "JioHotstar",
        "VI movies and tv"
      ]
    }
  },
  {
    "id": "the-lord-of-the-rings-the-two-towers",
    "title": "The Lord of the Rings: The Two Towers",
    "year": 2002,
    "kind": "Film",
    "genres": [
      "Adventure",
      "Fantasy",
      "Action"
    ],
    "runtime": 179,
    "brain": 0.5,
    "intensity": 0.69,
    "levity": 0.51,
    "score": 84,
    "hook": "The journey continues.",
    "poster": "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Netflix",
        "Stan",
        "Netflix Standard with Ads",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Netflix",
        "JioHotstar",
        "VI movies and tv"
      ]
    }
  },
  {
    "id": "inception",
    "title": "Inception",
    "year": 2010,
    "kind": "Film",
    "genres": [
      "Action",
      "Sci-Fi",
      "Adventure"
    ],
    "runtime": 148,
    "brain": 0.54,
    "intensity": 0.75,
    "levity": 0.48,
    "score": 84,
    "hook": "Your mind is the scene of the crime.",
    "poster": "https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    "providers": {
      "US": [
        "MGM Plus"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Amazon Prime Video",
        "Crave",
        "Hollywood Suite",
        "Starz Amazon Channel",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Netflix",
        "Amazon Prime Video",
        "Netflix Standard with Ads",
        "Amazon Prime Video with Ads"
      ],
      "IN": [
        "Amazon Prime Video",
        "JioHotstar",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "project-hail-mary",
    "title": "Project Hail Mary",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Sci-Fi",
      "Adventure"
    ],
    "runtime": 157,
    "brain": 0.64,
    "intensity": 0.61,
    "levity": 0.56,
    "score": 84,
    "hook": "Believe in the Hail Mary.",
    "poster": "https://image.tmdb.org/t/p/w500/yihdXomYb5kTeSivtFndMy5iDmf.jpg",
    "providers": {
      "US": [
        "Amazon Prime Video",
        "fuboTV",
        "MGM+ Amazon Channel",
        "Philo",
        "MGM Plus Roku Premium Channel",
        "MGM Plus",
        "Amazon Prime Video with Ads"
      ],
      "GB": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads",
        "MGM Plus Amazon Channel"
      ],
      "CA": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "AU": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "IN": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "interstellar",
    "title": "Interstellar",
    "year": 2014,
    "kind": "Film",
    "genres": [
      "Adventure",
      "Drama",
      "Sci-Fi"
    ],
    "runtime": 169,
    "brain": 0.76,
    "intensity": 0.6,
    "levity": 0.42,
    "score": 84,
    "hook": "Mankind was born on Earth. It was never meant to die here.",
    "poster": "https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    "providers": {
      "US": [
        "Hulu",
        "Paramount Plus Premium",
        "Paramount Plus Essential",
        "Paramount+ Amazon Channel",
        "Paramount+ Roku Premium Channel"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Netflix",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Netflix Standard with Ads",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "AU": [
        "Amazon Prime Video",
        "HBO Max",
        "Amazon Prime Video with Ads",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Amazon Prime Video",
        "JioHotstar",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "your-name",
    "title": "Your Name.",
    "year": 2016,
    "kind": "Film",
    "genres": [
      "Animation",
      "Romance",
      "Drama"
    ],
    "runtime": 106,
    "brain": 0.64,
    "intensity": 0.38,
    "levity": 0.52,
    "score": 84,
    "hook": "Separated by distance, connected by fate.",
    "poster": "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "AU": [
        "Crunchyroll Amazon Channel"
      ],
      "IN": [
        "Crunchyroll",
        "Sony Liv",
        "Crunchyroll Amazon Channel"
      ]
    }
  },
  {
    "id": "parasite",
    "title": "Parasite",
    "year": 2019,
    "kind": "Film",
    "genres": [
      "Comedy",
      "Thriller",
      "Drama"
    ],
    "runtime": 133,
    "brain": 0.65,
    "intensity": 0.62,
    "levity": 0.41,
    "score": 84,
    "hook": "Act like you own the place.",
    "poster": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    "providers": {
      "GB": [
        "MUBI",
        "BFI Player",
        "BFI Player Amazon Channel",
        "MUBI Amazon Channel",
        "Curzon Amazon Channel",
        "BFI Player Apple TV Channel",
        "ITVX Premium"
      ],
      "CA": [
        "Crave",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Hollywood Suite",
        "Hollywood Suite Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "IN": [
        "VI movies and tv"
      ]
    }
  },
  {
    "id": "pulp-fiction",
    "title": "Pulp Fiction",
    "year": 1994,
    "kind": "Film",
    "genres": [
      "Thriller",
      "Crime",
      "Comedy"
    ],
    "runtime": 154,
    "brain": 0.64,
    "intensity": 0.65,
    "levity": 0.38,
    "score": 84,
    "hook": "You won’t know the facts until you’ve seen the fiction.",
    "poster": "https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    "providers": {
      "US": [
        "fuboTV",
        "MGM+ Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Essential",
        "Philo",
        "Paramount+ Amazon Channel",
        "YouTube TV",
        "MGM Plus",
        "Paramount+ Roku Premium Channel"
      ],
      "GB": [
        "Amazon Prime Video",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Amazon Prime Video with Ads",
        "ITVX Premium",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "CA": [
        "Crave",
        "Super Channel Plus",
        "Super Channel Amazon Channel",
        "Hollywood Suite Amazon Channel",
        "fuboTV",
        "Starz Amazon Channel",
        "Crave Amazon Channel",
        "Lionsgate+ Amazon Channels"
      ],
      "AU": [
        "BINGE",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Foxtel Now",
        "Stan",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "IN": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "forrest-gump",
    "title": "Forrest Gump",
    "year": 1994,
    "kind": "Film",
    "genres": [
      "Comedy",
      "Drama",
      "Romance"
    ],
    "runtime": 142,
    "brain": 0.53,
    "intensity": 0.39,
    "levity": 0.66,
    "score": 84,
    "hook": "The world will never be the same once you've seen it through the eyes of Forrest Gump.",
    "poster": "https://image.tmdb.org/t/p/w500/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
    "providers": {
      "US": [
        "Paramount Plus Premium",
        "Paramount Plus Essential",
        "Peacock Premium",
        "Paramount+ Amazon Channel",
        "Peacock Premium Plus",
        "Wonder Project Amazon Channel"
      ],
      "GB": [
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "ITVX Premium",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "CA": [
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "AU": [
        "BINGE",
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Foxtel Now",
        "Stan",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "the-green-mile",
    "title": "The Green Mile",
    "year": 1999,
    "kind": "Film",
    "genres": [
      "Fantasy",
      "Drama",
      "Crime"
    ],
    "runtime": 189,
    "brain": 0.71,
    "intensity": 0.63,
    "levity": 0.33,
    "score": 84,
    "hook": "Paul Edgecomb didn't believe in miracles. Until the day he met one.",
    "poster": "https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    "providers": {
      "US": [
        "Philo",
        "AMC+ Roku Premium Channel",
        "AMC"
      ],
      "GB": [
        "Netflix",
        "Amazon Prime Video",
        "Sky Go",
        "Now TV Cinema",
        "Netflix Standard with Ads",
        "Amazon Prime Video with Ads",
        "Channel 4 Plus"
      ],
      "CA": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "AU": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "goodfellas",
    "title": "GoodFellas",
    "year": 1990,
    "kind": "Film",
    "genres": [
      "Drama",
      "Crime"
    ],
    "runtime": 145,
    "brain": 0.78,
    "intensity": 0.68,
    "levity": 0.26,
    "score": 84,
    "hook": "Three decades of life in the mafia.",
    "poster": "https://image.tmdb.org/t/p/w500/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg",
    "providers": {
      "US": [
        "fuboTV"
      ],
      "GB": [
        "Sky Go",
        "Now TV Cinema"
      ],
      "CA": [
        "Amazon Prime Video",
        "Crave",
        "Starz Amazon Channel",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "spider-man-into-the-spider-verse",
    "title": "Spider-Man: Into the Spider-Verse",
    "year": 2018,
    "kind": "Film",
    "genres": [
      "Animation",
      "Action",
      "Adventure"
    ],
    "runtime": 117,
    "brain": 0.48,
    "intensity": 0.6,
    "levity": 0.57,
    "score": 83,
    "hook": "Enter a universe where more than one wears the mask.",
    "poster": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Sky Go",
        "Now TV Cinema"
      ],
      "CA": [
        "Netflix",
        "Crave",
        "Netflix Standard with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Disney Plus",
        "Foxtel Now"
      ],
      "IN": [
        "Amazon Prime Video",
        "Sony Liv",
        "VI movies and tv",
        "Sony Pictures Amazon Channel",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "the-empire-strikes-back",
    "title": "The Empire Strikes Back",
    "year": 1980,
    "kind": "Film",
    "genres": [
      "Adventure",
      "Action",
      "Sci-Fi"
    ],
    "runtime": 124,
    "brain": 0.51,
    "intensity": 0.67,
    "levity": 0.5,
    "score": 83,
    "hook": "The Star Wars saga continues.",
    "poster": "https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    "providers": {
      "US": [
        "Disney Plus",
        "YouTube TV"
      ],
      "GB": [
        "Disney Plus"
      ],
      "CA": [
        "Disney Plus"
      ],
      "AU": [
        "Disney Plus"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "howl-s-moving-castle",
    "title": "Howl's Moving Castle",
    "year": 2004,
    "kind": "Film",
    "genres": [
      "Fantasy",
      "Animation",
      "Adventure"
    ],
    "runtime": 119,
    "brain": 0.51,
    "intensity": 0.48,
    "levity": 0.65,
    "score": 83,
    "hook": "The two lived there.",
    "poster": "https://image.tmdb.org/t/p/w500/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "Netflix",
        "Netflix Kids",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "life-is-beautiful",
    "title": "Life Is Beautiful",
    "year": 1997,
    "kind": "Film",
    "genres": [
      "Comedy",
      "Drama"
    ],
    "runtime": 116,
    "brain": 0.53,
    "intensity": 0.46,
    "levity": 0.54,
    "score": 83,
    "hook": "An unforgettable fable that proves love, family and imagination conquer all.",
    "poster": "https://image.tmdb.org/t/p/w500/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    "providers": {
      "US": [
        "Paramount Plus Premium",
        "Paramount Plus Essential",
        "Paramount+ Amazon Channel",
        "Paramount+ Roku Premium Channel"
      ],
      "CA": [
        "Paramount Plus",
        "Paramount+ Amazon Channel",
        "Paramount Plus Premium",
        "Paramount Plus Basic with Ads"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "IN": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "back-to-the-future",
    "title": "Back to the Future",
    "year": 1985,
    "kind": "Film",
    "genres": [
      "Adventure",
      "Comedy",
      "Sci-Fi"
    ],
    "runtime": 116,
    "brain": 0.56,
    "intensity": 0.48,
    "levity": 0.65,
    "score": 83,
    "hook": "He was never in time for his classes... He wasn't in time for his dinner... Then one day... he wasn't in his time at all.",
    "poster": "https://image.tmdb.org/t/p/w500/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
    "providers": {
      "US": [
        "AMC+ Amazon Channel"
      ],
      "GB": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "CA": [
        "Amazon Prime Video",
        "Netflix",
        "Crave",
        "Netflix Standard with Ads",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "BINGE",
        "Foxtel Now"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "se7en",
    "title": "Se7en",
    "year": 1995,
    "kind": "Film",
    "genres": [
      "Crime",
      "Thriller"
    ],
    "runtime": 127,
    "brain": 0.7,
    "intensity": 0.86,
    "levity": 0.2,
    "score": 83,
    "hook": "Gluttony. Greed. Sloth. Envy. Wrath. Pride. Lust.",
    "poster": "https://image.tmdb.org/t/p/w500/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    "providers": {
      "US": [
        "Peacock Premium",
        "Peacock Premium Plus"
      ],
      "GB": [
        "Sky Go",
        "Now TV Cinema"
      ],
      "CA": [
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ]
    }
  },
  {
    "id": "psycho",
    "title": "Psycho",
    "year": 1960,
    "kind": "Film",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "runtime": 109,
    "brain": 0.7,
    "intensity": 0.85,
    "levity": 0.26,
    "score": 83,
    "hook": "A new and altogether different screen excitement!",
    "poster": "https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
    "providers": {
      "GB": [
        "Sky Go",
        "Now TV Cinema"
      ],
      "CA": [
        "Crave",
        "Crave Amazon Channel"
      ],
      "AU": [
        "BINGE",
        "Foxtel Now"
      ]
    }
  },
  {
    "id": "the-silence-of-the-lambs",
    "title": "The Silence of the Lambs",
    "year": 1991,
    "kind": "Film",
    "genres": [
      "Crime",
      "Thriller",
      "Drama"
    ],
    "runtime": 119,
    "brain": 0.73,
    "intensity": 0.74,
    "levity": 0.27,
    "score": 83,
    "hook": "To enter the mind of a killer she must challenge the mind of a madman.",
    "poster": "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    "providers": {
      "US": [
        "fuboTV",
        "MGM+ Amazon Channel",
        "Philo",
        "YouTube TV",
        "Criterion Channel",
        "MGM Plus"
      ],
      "GB": [
        "MUBI",
        "MUBI Amazon Channel",
        "MGM Plus Amazon Channel"
      ],
      "CA": [
        "Crave",
        "Criterion Channel",
        "MGM Amazon Channel",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "BINGE",
        "Foxtel Now",
        "Stan",
        "MGM Amazon Channel"
      ],
      "IN": [
        "MGM Plus Amazon Channel"
      ]
    }
  },
  {
    "id": "the-sopranos",
    "title": "The Sopranos",
    "year": 1999,
    "kind": "Series",
    "genres": [
      "Crime",
      "Drama"
    ],
    "runtime": 60,
    "brain": 0.73,
    "intensity": 0.58,
    "levity": 0.29,
    "score": 83,
    "hook": "Family. Redefined.",
    "poster": "https://image.tmdb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Now TV",
        "HBO Max"
      ],
      "CA": [
        "Amazon Prime Video",
        "Crave",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Amazon Prime Video",
        "Foxtel Now",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "dilwale-dulhania-le-jayenge",
    "title": "Dilwale Dulhania Le Jayenge",
    "year": 1995,
    "kind": "Film",
    "genres": [
      "Comedy",
      "Drama",
      "Romance"
    ],
    "runtime": 190,
    "brain": 0.6,
    "intensity": 0.44,
    "levity": 0.57,
    "score": 82,
    "hook": "Come… fall In love, all over again…",
    "poster": "https://image.tmdb.org/t/p/w500/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "GB": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "AU": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "IN": [
        "Netflix"
      ]
    }
  },
  {
    "id": "the-matrix",
    "title": "The Matrix",
    "year": 1999,
    "kind": "Film",
    "genres": [
      "Action",
      "Sci-Fi"
    ],
    "runtime": 136,
    "brain": 0.61,
    "intensity": 0.74,
    "levity": 0.44,
    "score": 82,
    "hook": "Believe the unbelievable.",
    "poster": "https://image.tmdb.org/t/p/w500/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
    "providers": {
      "GB": [
        "HBO Max Amazon Channel",
        "HBO Max"
      ],
      "CA": [
        "Amazon Prime Video",
        "Crave",
        "Starz Amazon Channel",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Stan",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "Amazon Prime Video",
        "JioHotstar",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "rear-window",
    "title": "Rear Window",
    "year": 1954,
    "kind": "Film",
    "genres": [
      "Thriller",
      "Drama"
    ],
    "runtime": 113,
    "brain": 0.71,
    "intensity": 0.72,
    "levity": 0.29,
    "score": 82,
    "hook": "It only takes one witness to spoil the perfect crime.",
    "poster": "https://image.tmdb.org/t/p/w500/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
    "providers": {
      "US": [
        "YouTube TV",
        "TCM"
      ],
      "AU": [
        "BINGE",
        "Foxtel Now"
      ]
    }
  },
  {
    "id": "seven-samurai",
    "title": "Seven Samurai",
    "year": 1954,
    "kind": "Film",
    "genres": [
      "Action",
      "Drama"
    ],
    "runtime": 207,
    "brain": 0.65,
    "intensity": 0.82,
    "levity": 0.31,
    "score": 81,
    "hook": "Unmatched for suspense and spectacle!",
    "poster": "https://image.tmdb.org/t/p/w500/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "Philo",
        "YouTube TV",
        "Criterion Channel",
        "HBO Max"
      ],
      "GB": [
        "BFI Player",
        "BFI Player Amazon Channel",
        "BFI Player Apple TV Channel"
      ],
      "CA": [
        "Criterion Channel"
      ]
    }
  },
  {
    "id": "the-shining",
    "title": "The Shining",
    "year": 1980,
    "kind": "Film",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "runtime": 144,
    "brain": 0.67,
    "intensity": 0.96,
    "levity": 0.21,
    "score": 81,
    "hook": "A masterpiece of modern horror.",
    "poster": "https://image.tmdb.org/t/p/w500/uAR0AWqhQL1hQa69UDEbb2rE5Wx.jpg",
    "providers": {
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "Now TV Cinema",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Stan",
        "HBO Max",
        "HBO Max Amazon Channel"
      ]
    }
  },
  {
    "id": "alien",
    "title": "Alien",
    "year": 1979,
    "kind": "Film",
    "genres": [
      "Horror",
      "Sci-Fi"
    ],
    "runtime": 117,
    "brain": 0.63,
    "intensity": 0.75,
    "levity": 0.33,
    "score": 81,
    "hook": "In space no one can hear you scream.",
    "poster": "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    "providers": {
      "GB": [
        "Disney Plus"
      ],
      "CA": [
        "Disney Plus",
        "Crave",
        "Starz Amazon Channel",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Disney Plus"
      ]
    }
  },
  {
    "id": "the-wire",
    "title": "The Wire",
    "year": 2002,
    "kind": "Series",
    "genres": [
      "Crime",
      "Drama"
    ],
    "runtime": 94,
    "brain": 0.72,
    "intensity": 0.64,
    "levity": 0.29,
    "score": 81,
    "hook": "Listen carefully.",
    "poster": "https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Now TV",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Crave Amazon Channel"
      ],
      "AU": [
        "Foxtel Now",
        "HBO Max",
        "HBO Max Amazon Channel"
      ],
      "IN": [
        "JioHotstar",
        "VI movies and tv"
      ]
    }
  },
  {
    "id": "modern-times",
    "title": "Modern Times",
    "year": 1936,
    "kind": "Film",
    "genres": [
      "Comedy",
      "Drama",
      "Romance"
    ],
    "runtime": 87,
    "brain": 0.42,
    "intensity": 0.35,
    "levity": 0.63,
    "score": 80,
    "hook": "He stands alone as the greatest entertainer of modern times! No one on earth can make you laugh as heartily or touch your heart as deeply...the whole world laughs, cries and thrills to his priceless genius!",
    "poster": "https://image.tmdb.org/t/p/w500/7uoiKOEjxBBW0AgDGQWrlfGQ90w.jpg",
    "providers": {
      "US": [
        "Amazon Prime Video",
        "HBO Max Amazon Channel",
        "YouTube TV",
        "Criterion Channel",
        "HBO Max",
        "Amazon Prime Video with Ads"
      ],
      "GB": [
        "Amazon Prime Video",
        "Now TV",
        "Amazon Prime Video with Ads"
      ],
      "CA": [
        "Criterion Channel"
      ],
      "IN": [
        "Lionsgate Play",
        "Lionsgate Play Apple TV Channel",
        "Lionsgate Play Amazon Channel"
      ]
    }
  },
  {
    "id": "the-thing",
    "title": "The Thing",
    "year": 1982,
    "kind": "Film",
    "genres": [
      "Horror",
      "Thriller",
      "Sci-Fi"
    ],
    "runtime": 109,
    "brain": 0.67,
    "intensity": 0.82,
    "levity": 0.33,
    "score": 79,
    "hook": "Anytime. Anywhere. Anyone.",
    "poster": "https://image.tmdb.org/t/p/w500/tzGY49kseSE9QAKk47uuDGwnSCu.jpg",
    "providers": {
      "GB": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "CA": [
        "Amazon Prime Video",
        "Crave",
        "Hollywood Suite",
        "Hollywood Suite Amazon Channel",
        "Starz Amazon Channel",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ]
    }
  },
  {
    "id": "gabriel-s-inferno",
    "title": "Gabriel's Inferno",
    "year": 2020,
    "kind": "Film",
    "genres": [
      "Romance",
      "Drama"
    ],
    "runtime": 122,
    "brain": 0.59,
    "intensity": 0.4,
    "levity": 0.47,
    "score": 79,
    "hook": "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabr…",
    "poster": "https://image.tmdb.org/t/p/w500/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
    "providers": {
      "US": [
        "Passionflix Amazon Channel"
      ],
      "GB": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "the-punisher-one-last-kill",
    "title": "The Punisher: One Last Kill",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Action",
      "Drama",
      "Crime"
    ],
    "runtime": 51,
    "brain": 0.54,
    "intensity": 0.66,
    "levity": 0.29,
    "score": 78,
    "hook": "Hey Frank.",
    "poster": "https://image.tmdb.org/t/p/w500/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg",
    "providers": {
      "US": [
        "Disney Plus"
      ],
      "GB": [
        "Disney Plus"
      ],
      "CA": [
        "Disney Plus"
      ],
      "AU": [
        "Disney Plus"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "obsession",
    "title": "Obsession",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "runtime": 109,
    "brain": 0.63,
    "intensity": 0.86,
    "levity": 0.23,
    "score": 78,
    "hook": "Be careful who you wish for…",
    "poster": "https://image.tmdb.org/t/p/w500/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg"
  },
  {
    "id": "harakiri",
    "title": "Harakiri",
    "year": 1962,
    "kind": "Film",
    "genres": [
      "Action",
      "Drama"
    ],
    "runtime": 135,
    "brain": 0.72,
    "intensity": 0.65,
    "levity": 0.34,
    "score": 77,
    "hook": "What befalls others today, may be your own fate tomorrow.",
    "poster": "https://image.tmdb.org/t/p/w500/zK7HsOC7QxW1ldKIeFG8YJ5F2Eb.jpg",
    "providers": {
      "US": [
        "Criterion Channel"
      ],
      "CA": [
        "Criterion Channel"
      ]
    }
  },
  {
    "id": "gabriel-s-inferno-part-ii",
    "title": "Gabriel's Inferno: Part II",
    "year": 2020,
    "kind": "Film",
    "genres": [
      "Romance",
      "Drama"
    ],
    "runtime": 106,
    "brain": 0.57,
    "intensity": 0.39,
    "levity": 0.49,
    "score": 77,
    "hook": "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but…",
    "poster": "https://image.tmdb.org/t/p/w500/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
    "providers": {
      "US": [
        "Passionflix Amazon Channel"
      ],
      "GB": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "lee-cronin-s-the-mummy",
    "title": "Lee Cronin's The Mummy",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Horror",
      "Thriller"
    ],
    "runtime": 133,
    "brain": 0.67,
    "intensity": 0.85,
    "levity": 0.24,
    "score": 76,
    "hook": "What happened to Katie?",
    "poster": "https://image.tmdb.org/t/p/w500/1q308iixueCU4pFtSYugNOevtNx.jpg",
    "providers": {
      "US": [
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "Sky Go",
        "HBO Max"
      ],
      "CA": [
        "Crave"
      ],
      "AU": [
        "HBO Max",
        "HBO Max Amazon Channel"
      ]
    }
  },
  {
    "id": "hotarubi-no-mori-e",
    "title": "Hotarubi no Mori e",
    "year": 2011,
    "kind": "Film",
    "genres": [
      "Romance",
      "Animation",
      "Fantasy"
    ],
    "runtime": 45,
    "brain": 0.42,
    "intensity": 0.38,
    "levity": 0.68,
    "score": 76,
    "hook": "\"To sacrifice a whole life for one single touch...\"",
    "poster": "https://image.tmdb.org/t/p/w500/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg"
  },
  {
    "id": "senna",
    "title": "Senna",
    "year": 2010,
    "kind": "Film",
    "genres": [
      "Documentary"
    ],
    "runtime": 106,
    "brain": 0.91,
    "intensity": 0.34,
    "levity": 0.41,
    "score": 75,
    "hook": "No fear. No limits. No equal.",
    "poster": "https://image.tmdb.org/t/p/w500/nZbLCbRoP6iJq5sr8daHQzjnzFh.jpg",
    "providers": {
      "CA": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "IN": [
        "JioHotstar"
      ]
    }
  },
  {
    "id": "i-saw-the-devil",
    "title": "I Saw the Devil",
    "year": 2010,
    "kind": "Film",
    "genres": [
      "Thriller",
      "Horror"
    ],
    "runtime": 144,
    "brain": 0.61,
    "intensity": 0.96,
    "levity": 0.21,
    "score": 75,
    "hook": "Abandon all compassion.",
    "poster": "https://image.tmdb.org/t/p/w500/zp5NrmYp80axIGiEiYPmm1CW6uH.jpg",
    "providers": {
      "US": [
        "Philo"
      ],
      "AU": [
        "Foxtel Now"
      ],
      "IN": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  },
  {
    "id": "free-solo",
    "title": "Free Solo",
    "year": 2018,
    "kind": "Film",
    "genres": [
      "Documentary",
      "Adventure"
    ],
    "runtime": 100,
    "brain": 0.65,
    "intensity": 0.43,
    "levity": 0.52,
    "score": 74,
    "hook": "Live beyond fear.",
    "poster": "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
    "providers": {
      "US": [
        "Disney Plus",
        "Hulu",
        "fuboTV",
        "YouTube TV"
      ],
      "GB": [
        "Disney Plus"
      ],
      "CA": [
        "Disney Plus"
      ],
      "AU": [
        "Disney Plus"
      ]
    }
  },
  {
    "id": "friends-the-reunion",
    "title": "Friends: The Reunion",
    "year": 2021,
    "kind": "Film",
    "genres": [
      "Documentary"
    ],
    "runtime": 104,
    "brain": 0.9,
    "intensity": 0.33,
    "levity": 0.41,
    "score": 73,
    "hook": "The one where they get back together.",
    "poster": "https://image.tmdb.org/t/p/w500/bT3c4TSOP8vBmMoXZRDPTII6eDa.jpg",
    "providers": {
      "US": [
        "HBO Max Amazon Channel",
        "YouTube TV",
        "HBO Max"
      ],
      "GB": [
        "HBO Max Amazon Channel",
        "HBO Max"
      ],
      "CA": [
        "Crave",
        "Crave Amazon Channel"
      ],
      "AU": [
        "HBO Max",
        "HBO Max Amazon Channel"
      ]
    }
  },
  {
    "id": "citizenfour",
    "title": "Citizenfour",
    "year": 2014,
    "kind": "Film",
    "genres": [
      "Documentary"
    ],
    "runtime": 113,
    "brain": 0.91,
    "intensity": 0.34,
    "levity": 0.41,
    "score": 73,
    "hook": "In June 2013, Laura Poitras and reporter Glenn Greenwald flew to Hong Kong for the firs…",
    "poster": "https://image.tmdb.org/t/p/w500/nOVhX69EAxtSKEEnr5UcSd5UVci.jpg",
    "providers": {
      "US": [
        "Philo"
      ],
      "CA": [
        "Sundance Now Amazon Channel",
        "AMC+ Amazon Channel",
        "Sundance Now Apple TV Channel"
      ],
      "AU": [
        "Foxtel Now",
        "DocPlay",
        "DocPlay Amazon Channel"
      ]
    }
  },
  {
    "id": "amy",
    "title": "Amy",
    "year": 2015,
    "kind": "Film",
    "genres": [
      "Documentary",
      "Drama"
    ],
    "runtime": 128,
    "brain": 0.73,
    "intensity": 0.36,
    "levity": 0.55,
    "score": 72,
    "hook": "The girl behind the name.",
    "poster": "https://image.tmdb.org/t/p/w500/qL0RepWSNUuZoeDXfyhqowVYhrn.jpg",
    "providers": {
      "US": [
        "Netflix",
        "Netflix Standard with Ads"
      ],
      "CA": [
        "Amazon Prime Video",
        "AMC+ Amazon Channel",
        "Starz Amazon Channel",
        "Amazon Prime Video with Ads",
        "Crave Amazon Channel"
      ]
    }
  },
  {
    "id": "bowling-for-columbine",
    "title": "Bowling for Columbine",
    "year": 2002,
    "kind": "Film",
    "genres": [
      "Documentary",
      "Drama"
    ],
    "runtime": 120,
    "brain": 0.82,
    "intensity": 0.48,
    "levity": 0.35,
    "score": 72,
    "hook": "Are we a nation of gun nuts or are we just nuts?",
    "poster": "https://image.tmdb.org/t/p/w500/4XsiTsZcNCRSkee1o0fdr5OqYRT.jpg",
    "providers": {
      "US": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "GB": [
        "Now TV"
      ],
      "CA": [
        "Lionsgate+ Amazon Channels"
      ],
      "AU": [
        "Foxtel Now",
        "DocPlay",
        "DocPlay Amazon Channel"
      ]
    }
  },
  {
    "id": "disclosure-day",
    "title": "Disclosure Day",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Sci-Fi",
      "Thriller"
    ],
    "runtime": 146,
    "brain": 0.69,
    "intensity": 0.75,
    "levity": 0.33,
    "score": 66,
    "hook": "We deserve to know.",
    "poster": "https://image.tmdb.org/t/p/w500/9XKXO68h0KGMCQ9ZZEdP0DWfcXS.jpg"
  },
  {
    "id": "your-heart-will-be-broken",
    "title": "Your Heart Will Be Broken",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Romance"
    ],
    "runtime": 134,
    "brain": 0.43,
    "intensity": 0.31,
    "levity": 0.64,
    "score": 66,
    "hook": "High school student Polina is saved from bullying at her new school and makes a deal wi…",
    "poster": "https://image.tmdb.org/t/p/w500/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg"
  },
  {
    "id": "citizen-vigilante",
    "title": "Citizen Vigilante",
    "year": 2026,
    "kind": "Film",
    "genres": [
      "Thriller",
      "Action",
      "Crime"
    ],
    "runtime": 89,
    "brain": 0.53,
    "intensity": 0.84,
    "levity": 0.33,
    "score": 65,
    "hook": "An action film inspired by real events.",
    "poster": "https://image.tmdb.org/t/p/w500/6LmJD3Wohe0g4U62wgi7RyJqfE4.jpg"
  },
  {
    "id": "12-angry-men",
    "title": "12 Angry Men",
    "year": 1957,
    "kind": "Film",
    "genres": [
      "Drama"
    ],
    "runtime": 97,
    "brain": 0.71,
    "intensity": 0.48,
    "levity": 0.32,
    "score": 84,
    "hook": "It explodes like 12 sticks of dynamite!",
    "poster": "https://image.tmdb.org/t/p/w500/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg",
    "providers": {
      "US": [
        "Amazon Prime Video",
        "MGM Plus",
        "Amazon Prime Video with Ads"
      ],
      "GB": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "CA": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ],
      "AU": [
        "Amazon Prime Video",
        "Foxtel Now",
        "Amazon Prime Video with Ads"
      ],
      "IN": [
        "Amazon Prime Video",
        "Amazon Prime Video with Ads"
      ]
    }
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GENRES, MOOD_AXES, CATALOG };
} else {
  const root = typeof window !== 'undefined' ? window : globalThis;
  root.GENRES = GENRES;
  root.MOOD_AXES = MOOD_AXES;
  root.CATALOG = CATALOG;
}
